swagger: '2.0'
info:
  description: Набор сервисов для работы с системой финансового, складского и оперативного учета организации ООО "Ромашка"
  version: "1.0.0"
  title: RestAPI
consumes:
  - application/json
produces:
  - application/json  
basePath: "/api"  
paths:
    /nomenclature:
      get:
        tags:
          - nomenclature
        summary: Получить список номерклатуры
        operationId: main.get_nomenclature
        responses:
          200:
            description: OK
            schema:
              type: object
              properties:
                nomenclature:
                  type: array
                  items:
                    type: string

    /nomenclature/groups:
      get:
        tags:
          - nomenclature
        summary: Получить список групп номерклатуры
        operationId: main.get_nomenclature_groups
        responses:
          200:
            description: OK
            schema:
              type: object
              properties:
                nomenclature:
                  type: array
                  items:
                    type: string

    /nomenclature/units:
      get:
        tags:
          - nomenclature      
        summary: Получить список единиц измерения
        operationId: main.get_nomenclature_units
        responses:
          200:
            description: OK
            schema:
              type: object
              properties:
                nomenclature:
                  type: array
                  items:
                    type: string                    

    